version: '3'
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.7
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.evo
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
    networks:
      - musad-bot-n8n_backnet
volumes:
  evolution_store:
  evolution_instances:

networks:
  musad-bot-n8n_backnet:
    external: true