apiVersion: apps/v1
kind: Deployment
metadata:
  name: kleem-api
  labels:
    app: kleem-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kleem-api
  template:
    metadata:
      labels:
        app: kleem-api
    spec:
      containers:
        - name: api
          image: kleem/api:1.0.0 # لا تستخدم latest في الإنتاج
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '3000'
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: kleem-secrets
                  key: mongodb-uri
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: kleem-secrets
                  key: redis-url
          resources:
            requests:
              cpu: '250m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          livenessProbe:
            httpGet:
              path: /api/health/liveness
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health/readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ['/bin/sh', '-c', 'sleep 10']
      terminationGracePeriodSeconds: 30
