route:
  receiver: 'telegram'
  group_by: ['alertname']
receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: 'YOUR_TELEGRAM_BOT_TOKEN'
        chat_id: YOUR_CHAT_ID
        parse_mode: 'HTML'
        message: |
          <b>{{ .CommonAnnotations.summary }}</b>
          {{ range .Alerts }}
          <pre>{{ .Annotations.description }}</pre>
          {{ end }}
