global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: kaleem

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['kaleem-alertmanager:9093'] # كان alertmanager:9093

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # كان prometheus:9090

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['kaleem-rabbitmq:15692'] # كان rabbitmq:15692

  - job_name: 'redis'
    static_configs:
      - targets: ['kaleem-redis-exporter:9121'] # كان redis-exporter:9121

  - job_name: 'mongodb'
    static_configs:
      - targets: ['kaleem-mongodb-exporter:9216'] # كان mongodb-exporter:9216

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['kaleem-cadvisor:8080'] # كان cadvisor:8080

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['kaleem-api:3000'] # كان api:3000

  - job_name: 'ai-reply-worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['kaleem-ai-reply:9101'] # كان ai-reply-worker:9101

  - job_name: 'webhook-dispatcher'
    metrics_path: /metrics
    static_configs:
      - targets: ['kaleem-webhook-dispatcher:9102'] # كان webhook-dispatcher:9102

  - job_name: 'indexing-worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['kaleem-indexing:9103'] # كان indexing-worker:9103
