global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: kaleem

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'cadvisor' # داخل الشبكة، لا داعي لفتح بورت خارجي
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'api' # تأكد PORT=3000 في خدمة الـAPI
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3000']

  - job_name: 'ai-reply-worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['ai-reply-worker:9101']

  - job_name: 'webhook-dispatcher'
    metrics_path: /metrics
    static_configs:
      - targets: ['webhook-dispatcher:9102']

  - job_name: 'indexing-worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['indexing-worker:9103']
