receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  otlphttp/tempo:
    endpoint: http://tempo:3200
    url_path: /api/traces
  debug:
    verbosity: basic

extensions:
  health_check:
  cors:
    allowed_origins:
      - https://kaleem-ai.com
      - https://*.kaleem-ai.com
    allowed_headers:
      [
        'Content-Type',
        'Accept',
        'User-Agent',
        'Traceparent',
        'Baggage',
        'Authorization',
      ]
    max_age: 7200

service:
  telemetry:
    logs:
      level: 'info'
    metrics:
      address: '0.0.0.0:8889'
  extensions: [health_check, cors]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo]
