// src/common/constants/error-codes.ts

/** أكواد الأخطاء الموحدة للنظام */
export const ERROR_CODES = {
  // أخطاء عامة
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',

  // أخطاء المصادقة
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // أخطاء الأعمال
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  ORDER_ALREADY_PROCESSED: 'ORDER_ALREADY_PROCESSED',
  PRODUCT_NOT_AVAILABLE: 'PRODUCT_NOT_AVAILABLE',

  // أخطاء التكامل
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  WEBHOOK_FAILED: 'WEBHOOK_FAILED',
  INTEGRATION_ERROR: 'INTEGRATION_ERROR',

  // أخطاء الملفات
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // أخطاء قاعدة البيانات
  DATABASE_ERROR: 'DATABASE_ERROR',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',

  // أخطاء الويب سوكيت
  WS_ERROR: 'WS_ERROR',
  WS_CONNECTION_FAILED: 'WS_CONNECTION_FAILED',

  // أخطاء المحادثة والذكاء الاصطناعي
  CHAT_SESSION_NOT_FOUND: 'CHAT_SESSION_NOT_FOUND',
  CHAT_MESSAGE_TOO_LONG: 'CHAT_MESSAGE_TOO_LONG',
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
  AI_RATE_LIMIT_EXCEEDED: 'AI_RATE_LIMIT_EXCEEDED',
  AI_INVALID_RESPONSE: 'AI_INVALID_RESPONSE',

  // أخطاء القنوات والتواصل
  CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
  CHANNEL_DISABLED: 'CHANNEL_DISABLED',
  CHANNEL_CONFIG_ERROR: 'CHANNEL_CONFIG_ERROR',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',

  // أخطاء التاجر والمتجر
  MERCHANT_DISABLED: 'MERCHANT_DISABLED',
  STOREFRONT_NOT_FOUND: 'STOREFRONT_NOT_FOUND',
  STOREFRONT_DISABLED: 'STOREFRONT_DISABLED',

  // أخطاء التحليلات
  ANALYTICS_DATA_NOT_FOUND: 'ANALYTICS_DATA_NOT_FOUND',
  ANALYTICS_QUERY_INVALID: 'ANALYTICS_QUERY_INVALID',

  // أخطاء الإشعارات
  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',
  NOTIFICATION_TEMPLATE_NOT_FOUND: 'NOTIFICATION_TEMPLATE_NOT_FOUND',

  // أخطاء N8N
  N8N_WORKFLOW_NOT_FOUND: 'N8N_WORKFLOW_NOT_FOUND',
  N8N_WORKFLOW_EXECUTION_FAILED: 'N8N_WORKFLOW_EXECUTION_FAILED',
  N8N_API_ERROR: 'N8N_API_ERROR',

  // أخطاء الفيكتور والبحث
  VECTOR_INDEX_ERROR: 'VECTOR_INDEX_ERROR',
  VECTOR_SEARCH_ERROR: 'VECTOR_SEARCH_ERROR',
  EMBEDDING_GENERATION_FAILED: 'EMBEDDING_GENERATION_FAILED',

  // أخطاء الكتالوج
  CATALOG_SYNC_FAILED: 'CATALOG_SYNC_FAILED',
  CATALOG_ITEM_NOT_FOUND: 'CATALOG_ITEM_NOT_FOUND',

  // أخطاء الويب هوك
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_PAYLOAD_INVALID: 'WEBHOOK_PAYLOAD_INVALID',
  WEBHOOK_RATE_LIMIT_EXCEEDED: 'WEBHOOK_RATE_LIMIT_EXCEEDED',

  // أخطاء الميديا
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  MEDIA_PROCESSING_FAILED: 'MEDIA_PROCESSING_FAILED',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',

  // أخطاء التصنيف
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CATEGORY_CYCLE_DETECTED: 'CATEGORY_CYCLE_DETECTED',

  // أخطاء التكامل مع الخدمات الخارجية
  TELEGRAM_API_ERROR: 'TELEGRAM_API_ERROR',
  WHATSAPP_API_ERROR: 'WHATSAPP_API_ERROR',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',

  // أخطاء الترخيص والحدود
  LICENSE_EXPIRED: 'LICENSE_EXPIRED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',

  // أخطاء الأمان
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  IP_BLOCKED: 'IP_BLOCKED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
