# تحتوي على Python + Playwright + المتصفحات على Ubuntu Jammy
FROM mcr.microsoft.com/playwright/python:v1.47.0-jammy

WORKDIR /app
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .
EXPOSE 8001
CMD ["dumb-init", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
